'''
This file contains all the paths
'''
sample_data_path = '/home/santosh_0212/computer_vision_mastery/data'
sample_img_path = f'{sample_data_path}/starter_images/sample_images'
filtered_sample_img_path = f'{sample_data_path}/starter_images/filtered_sample_images'
gradient_demo_img_path = f'{sample_data_path}/edge_detection/gradients_demo_img'
nms_demo_img_path = f'{sample_data_path}/edge_detection/NMS_demo_img'
double_threshold_img_path = f'{sample_data_path}/edge_detection/double_thresholding_demo_img'
hysteresis_img_path = f'{sample_data_path}/edge_detection/hysteresis_demo_img'
canny_edge_comparison_img_path = f'{sample_data_path}/edge_detection/canny_edge_comparison_demo_img'
harris_demo_img_path = f'{sample_data_path}/feature_detection/harris_feature_detection_demo_img'
harris_comparison_demo_img_path = f'{sample_data_path}/feature_detection/harris_comparison_demo_img'
shi_tomasi_demo_img_path = f'{sample_data_path}/feature_detection/shi_tomasi_demo_img'
fast_demo_img_path = f'{sample_data_path}/feature_detection/FAST_demo_img'
orb_demo_img_path = f'{sample_data_path}/feature_detection/ORB_demo_img'
orb_feature_matching_demo_img_path = f'{sample_data_path}/feature_detection/ORB_feature_matching_demo_img'
refined_orb_matching_demo_img_path = f'{sample_data_path}/feature_detection/knn_lowe_ratio_ORB_demo_img'